### ISSUE TITLE
i don't undersatnd how this works?

### ISSUE THREAD

**Issue by Leo01985** [mohan3d/PyOpenload#10]
is posible to make some script like this https://github.com/ArdiArtani/Google-Drive-Player-Script this is for google drive, i don't know if is posible to make same for openload?

**Comment by mohan3d** [comment]
Hi @Leo01985 

PyOpenload documentation is [available](https://pyopenload.readthedocs.io/en/latest/overview.html), it may help you understand what is PyOpenload.

[Pyopenload](https://github.com/mohan3d/PyOpenload) is just a wrapper for [openload.co API](https://openload.co/api) in python,
you can do anything that can be done with the API.

If I understand what [this project](https://github.com/ArdiArtani/Google-Drive-Player-Script) does, then you can do the same with openload/pyopenload.

- use pyopenload to download videos from openload account.
- provide direct url to your javaScript player (jwplayer, videojs, flowplayer etc).


but there are problems you have to deal with.
- You will write a code to download videos ([openload.co](openload.co) gives you direct download url).
- Sometimes openload requires captcha to be solved before giving you direct download url.
- At peak hours openload will not give you download url.
