### ISSUE TITLE
'solve_captcha' is not defined

### ISSUE THREAD

**Issue by VikasRana** [mohan3d/PyOpenload#12]
It raises this error that 'solve_captcha' is not defined. Also do I have to manually solve the captcha or is the script going to do it?

**Comment by mohan3d** [comment]
Hi VikasRana,

It seems you ran an example without providing your implementation of `solve_captcha`.

Sometimes [openload](https://openload.co/) sends captcha to be solved, you have to implement a way to solve these captcha as mention [here](https://pyopenload.readthedocs.io/en/latest/tutorial.html#download).

No this script doesn't solve the captcha, It's just a wrapper for [openload API](https://openload.co/api).

**Comment by mohan3d** [comment]
Closed, no response for a long time.
