### ISSUE TITLE
ImportError: cannot import name 'OpenLoad'

### ISSUE THREAD

**Issue by harunresitc** [mohan3d/PyOpenload#13]
My file:
`#!/usr/bin/env python

from openload import OpenLoad

def openLoader(file):

    login="login"
    key="pass"

    ol = OpenLoad(login, key)

    uploaded_file_info = ol.upload_file(file)
    print(uploaded_file_info)

openLoader("cover.jpg")`

Error:
`Traceback (most recent call last):
  File "/home/pi/Desktop/openloadAPI/openload.py", line 3, in <module>
    from openload import OpenLoad
  File "/home/pi/Desktop/openloadAPI/openload.py", line 3, in <module>
    from openload import OpenLoad
ImportError: cannot import name 'OpenLoad'`

**Comment by mohan3d** [comment]
Hi @harunresitc 

Is your file name `openload.py`? please try to rename it to `demo.py` or anything other than `openload.py` and try again.

**Comment by harunresitc** [comment]
demo.py:
`#!/usr/bin python3

from openload import OpenLoad

def openLoader(file):

    login="e87124469ff01be1"
    key="resit1985"

    ol = OpenLoad(login, key)

    uploaded_file_info = ol.upload_file(file)
    print(uploaded_file_info)

openLoader("cover.jpg")`

ERROR:
`Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from openload import OpenLoad
ImportError: No module named 'openload'
`

**Comment by mohan3d** [comment]
Please make sure you installed `pyopenload `properly using pip, verify it using pip list.

Also provide me with python and pip version in order for me to test with the same setup.

**Comment by mohan3d** [comment]
You can check if a package is installed either using `pip list` then check if the package exist 
or `pip show pyopenload` it should output something like this 

```
Name: pyopenload
Version: 0.5
Summary: Python wrapper for openload.co API
Home-page: https://github.com/mohan3d/PyOpenload
Author: Mohaned Magdy
Author-email: mohan3d94@gmail.com
License: MIT
Location: <PATH>
Requires: requests
```

`python --version` to get your installed python version, 
`pip --version` to get your installed pip version.

btw it's not a good idea to install packages using sudo, please take a look at [virtualenv](https://virtualenv.pypa.io/en/latest/) or [pipenv](https://pipenv.readthedocs.io/en/latest/) projects.

**Comment by mohan3d** [comment]
Closed, no response for a long time.
