### ISSUE TITLE
Loop upload Error

### ISSUE THREAD

**Issue by Ray7910** [mohan3d/PyOpenload#15]
Hi 
When I do this code:

```
uploaded_file_info = ol.upload_file(c:\video\file.mp4)
print(uploaded_file_info)
```

It works just fine

But when I try to loop from a CSV file 
it give the error below:

```
_with open('ListTest.1.csv', 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    next(csv_reader)
    for line in csv_reader:
        print(line)
        
        name = (line[0])
        VidPath = (line[4])
        

        print(name)
        print(VidPath)

        uploaded_file_info = ol.upload_file(VidPath)
        print(uploaded_file_info)_ 
```
Traceback :     
```
Traceback (most recent call last):
  File "PrintingTest.py", line 19, in <module>
    uploaded_file_info = ol.upload_file(VidPath)
  File "C:\Users\resta\Anaconda3\lib\site-packages\openload\openload.py", line 258, in upload_file
    files={'upload_file': open(file_path, 'rb')}).json()
OSError: [Errno 22] Invalid argument: ' c:\video\file.mp4'
```
What am I doing wrong?

**Comment by mohan3d** [comment]
Hi @Ray7910 ,

It seems there is a problem with your paths in CSV file, 

`OSError: [Errno 22] Invalid argument: ' c:\video\file.mp4'`

There is a leading space before the file path, make sure to get rid of leading/trailing spaces from the file or for a quick check `uploaded_file_info = ol.upload_file(VidPath.strip())`.

**Comment by mohan3d** [comment]
HI @Ray7910 ,

Are you still facing this problem?

**Comment by Ray7910** [comment]
No, I fix it. It working just fine now, tnx.

But I have an other issue. I have been trying to remote upload but it only
gives an error.
Do you have any examples of how to do that of which kind of link do I need
to get?
is it the post link or the video link?

**Comment by mohan3d** [comment]
Hi @Ray7910 , 

Your remote upload url must be a direct url (once clicked a download starts).

Please take look at the examples in the [documentation](https://pyopenload.readthedocs.io/en/latest/examples.html#remote-upload).

Another example

```
from openload import OpenLoad

ol = OpenLoad('login', 'key')

url = 'https://dl1.filehippo.com/36e66efa297542208ed660b608c1bf45/Viber.dmg?ttl=1549381766&token=b90432eb21db5c74883499a2bb18193d'

r = ol.remote_upload(url)
print(r)
```

**Comment by mohan3d** [comment]
Hi @Ray7910 , 

Are you still facing the same problem?

**Comment by Ray7910** [comment]
Yes,
For example, I try to remote upload but still not working. Let's say I'm
trying xhamster. This specific  link
https://xhamster.com/videos/aj-applegate-gives-her-asshole-for-valentine-s-day-11043214
I found 2 links:

1. <video preload="auto" src="blob:
https://xhamster.com/63124984-99f5-4e5f-a022-7c875f708513"></video>

2. <a href="
https://19-12.b.cdn13.com/011/043/214/720p.h264.mp4?cdn_creation_time=1550192400&amp;cdn_ttl=14400&amp;cdn_bw=290k&amp;cdn_bw_fs=385k&amp;cdn_cv_data=2001%3A1c00%3A1619%3Ab300%3A99f3%3A9d65%3A7bc8%3Af9fb-dvp&amp;cdn_hash=5345c117d55138de0a9f35798bece99b
"

But none of them seems to work. Am I getting the wrong links or it just
don't work?

**Comment by mohan3d** [comment]
Hi @Ray7910 , 

You are accessing the wrong urls, you need to access direct download url as I said before, 
after checking your urls (some of the didn't load).

For the url you provided, the direct url would be [this](https://1-399-19-12.b.cdn13.com//011//043//214//720p.h264.mp4?cdn_creation_time=1550239200&cdn_ttl=14400&cdn_bw=290k&cdn_bw_fs=385k&cdn_cv_data=42.61.197.126-dvp&cdn_hash=c13efdd2f2e05154880d903973c49904) for 720p.

The problem is how you parse/get the direct URL not the pyopenload.

**Comment by mohan3d** [comment]
Closed: no response for a long time.
