### ISSUE TITLE
Can't upload file - Memory Error

### ISSUE THREAD

**Issue by Barbait** [mohan3d/PyOpenload#18]
Hi, i've wrote some code to upload every file in a folder.

I take the files from an output folder (the files are processed beforehand by removing the space in the name), i've double checked that the files are in the correct folder.

This is the code:
```
mainol = OpenLoad(configacc['main']['login'], configacc['main']['key'])

outfiles = os.listdir(outputdir)

for filename in outfiles:
    print(f"Starting to upload file: {filename}")
    fullpath = outputdir + '\\' + filename
    print(fullpath)
# the path prints correctly.
    uploaded_file_info = mainol.upload_file(fullpath)
```

The error that the interpreter returns is:

```
Traceback (most recent call last):
  File "C:/Users/user/Desktop/Python_dev/openloadupper/main.py", line 200, in <module>
    uploaded_file_info = mainol.upload_file(fullpath)
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\openload\openload.py", line 258, in upload_file
    files={'upload_file': open(file_path, 'rb')}).json()
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\requests\models.py", line 504, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\requests\models.py", line 169, in _encode_files
    body, content_type = encode_multipart_formdata(new_fields)
  File "C:\Users\user\Desktop\Python_dev\openloadupper\venv\lib\site-packages\urllib3\filepost.py", line 92, in encode_multipart_formdata
    body.write(b'\r\n')
MemoryError
```

Any help is appreciated.

**Comment by mohan3d** [comment]
Hi @Barbait ,

Can you provide me with some info? 

Your environment, python version, ...
Average size of your files.

**Comment by Barbait** [comment]
yeah of course!

python version 3.7, ran everything with pycharm in virtualenv (also tried from the windows cmd)

i got 8gb of ram and an i7 with win10 on my laptop (running the script from the desktop and the path doesn't have any space in it, also the files are processed to remove the space and use an underscore instead)

the average file size is between 500Mb and 800Mb

the thing is i rewrote the entire script from scratch and worked fine. But suddently and sporadically the problem appeared again

**Comment by mohan3d** [comment]
Are you running python x32? 

Do you load all your files directly to the memory for processing and uploading? it might be you cannot fit all of them into the memory?

Please take a look on this [answer](https://stackoverflow.com/a/5537759).

**Comment by Barbait** [comment]
i don't know how to reply, how could i check it?

**Comment by mohan3d** [comment]
> i don't know how to reply, how could i check it?

Please follow one of the solutions [here](https://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os).

The easiest one is to start a new python shell you will notice is it win32 or win64.

Or run this in you CMD  `python -c 'import struct; print(struct.calcsize("P") * 8)'`

**Comment by Barbait** [comment]
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

that's what i see when i open python with the cmd, anyway i'm pretty sure when i downloaded it was 64 bit.

**Comment by mohan3d** [comment]
Can you try with fewer files (total size of files can fit into your memory)? 

It seems the issue is that you load many files at the same time, I am not sure if uploading process is related.

**Comment by Barbait** [comment]
With 14 files (total of 6Gb) the problem still persists. I tried also with 1 files (534Mb) and i got the error as well.

**Comment by mohan3d** [comment]
This is not normal, 0.5 GB should fit into you memory regardless is python x64 or x32.

Can you write a script only to read file and upload it (don't process the files in the same code)?

**Comment by Barbait** [comment]
Even if commenting out the first part of the script (that simply renamed the files) i got memory error. Now i rebooted my pc and tried again, without results. I am still getting the error.

**Comment by mohan3d** [comment]
Can you share some of your code?

**Comment by Barbait** [comment]
Yeah, no problem. This is the code i'm using: https://pastebin.com/aDVe3KU8
In order to work correctly you can use files named "Seriesname--S1-E00-EPtitle.something" in either video\input or video\output folder

**Comment by mohan3d** [comment]
Could you please try with only upload part?

This code is enough to test it.

``` python
import os

from openload import OpenLoad

ol = OpenLoad('<LOGIN>', '<KEY>')

for path in os.listdir('YOUR_VIDEOS_DIRECTORY_PATH'):
    uploaded_file_info = ol.upload_file(path)
```

**Comment by Barbait** [comment]
<a href="https://ibb.co/Y36ZQtn"><img src="https://i.ibb.co/Y36ZQtn/Cattura.png" alt="Cattura" border="0"></a>

This is what i get. There the problem is that the path variable contains only the name of the file, if i fix it by passing the full path of the files it gaves me the Memory Error again

**Comment by mohan3d** [comment]
is your memory really full while this code is running? 

I asked earlier you said you tried with fewer files and still getting the same error, this error is not supposed to be thrown unless memory is really full.

> With 14 files (total of 6Gb) the problem still persists. I tried also with 1 files (534Mb) and i got the error as well.

There is no way for this to happen if you only loaded one file with size of 0.5GB.

Did you check with this small code with full path files? only few of them one file or two?

**Comment by Barbait** [comment]
I checked with only one file in the folder, i have about 60% of free memory.
I also checked by removing the for loop and parsing the file's full path directly into the function, but still the memory error appears

**Comment by Barbait** [comment]
After formatting my pc and setting up everything again it doesn't work still.

**Comment by mohan3d** [comment]
Hello @Barbait ,

I have updated [pyopenload](https://github.com/mohan3d/PyOpenload) to support large files, using [requests-toolbelt](https://github.com/requests/toolbelt).

Please install the latest version and try again.

`pip install --upgrade pyopenload`

**Comment by mohan3d** [comment]
Not active for a long time.
