### ISSUE TITLE
API alternatives

### ISSUE THREAD

**Issue by Mixanologos** [mohan3d/PyOpenload#2]
Hello mohan3d and thank you for the tool. 

I just have one question in case someone didn't want to use the API what other alternatives would be available to upload files using python?

**Comment by mohan3d** [comment]
You may create some requests to `openload ` without using the API.

- Login to your account (post request `https://openload.co/login` with `emai/password`)
- Navigate to the `file manager` (get request `https://openload.co/account#fileman`)
- Generate `upload url` (used to upload files)
- Upload files (post request `upload url`)

Here is a quick & dirty [script ](https://gist.github.com/mohan3d/b2e1dc9240383d35de835d5c95c71799) using `requests`

Note: `openload` sends code to your email if login is not recognized, you need to enter it.

**Comment by Mixanologos** [comment]
You are awesome! Thanks a lot for taking the time to answer me,let alone code the script.

**Comment by mohan3d** [comment]
It's my pleasure.
