### ISSUE TITLE
Not working with the file which has non-Ascii filename.

### ISSUE THREAD

**Issue by junjxie** [mohan3d/PyOpenload#24]
Traceback (most recent call last):
  File "/root/py/vsmanu.py", line 15, in <module>
    uploaded_file_info = vs.upload_file(fullpath)
  File "/usr/local/lib/python3.6/dist-packages/verystream/verystream.py", line 266, in upload_file
    response_json = requests.post(upload_url, data=data, headers=headers).json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 340, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 358, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The problem only occurs when file has non-Ascii filename.

**Comment by mohan3d** [comment]
Hello @penjune , 

Can you please provide more info?
- **pyopenload** version
- python version (I assume it's 3.6 from the path)

Did you try with different file name?
If possible can you provide the file name?

I tried to follow this [issue](https://github.com/psf/requests/issues/3446) created a file with the same name, as mentioned [here](https://github.com/psf/requests/issues/3446#issuecomment-235575351) I got an error message from the server side.
```
raise ServerErrorException(msg)
openload.api_exceptions.ServerErrorException: upload failed
```

**Comment by junjxie** [comment]
My pyopenload is newest version, but I replaced openload with verystream.
Same file with only english filename could be uploaded successfully.
file name : testアニメ.mp4
Successfully uploaded file name：test.mp4

**Comment by mohan3d** [comment]
I tried again with these names

- testアニメ.mp4
- アニメ.mp4

Both of them weren't uploaded successfully but clearly this is a server side problem since I get 
`openload.api_exceptions.ServerErrorException: upload failed` exception.

If you don't get this exception (which is the normal behaviour), please try again with new virtualenv with **pyopenload** installed (to make sure dependencies also updated).

**Comment by junjxie** [comment]
I've done some test on my vps today.
I successfully uploaded testアニメ.mp4 to verystream on my debian one , 
while failed on my ubuntu one.
So maybe it was my ubuntu vps's problem.
Thanks for your help and replies !

P.S.
Actually I do not have any openload account.
I have tried to register several times , 
but did not received any confirmation mail after registration.

**Comment by mohan3d** [comment]
Yeah I noticed **openload** has some issues in last two days (might be even before this).
I couldn't login in last two days.
