### ISSUE TITLE
getting File ID from upload.  

### ISSUE THREAD

**Issue by mrleadhead** [mohan3d/PyOpenload#3]
Hi, 

code works brilliantly... I'm just suck on how to get the file ID when I upload a file can you point me in the right direction. 

Thanks.

**Comment by mohan3d** [comment]
Hi @mrleadhead ,

If you used pyopenload to upload it, you will find file id in the response.

![capture](https://user-images.githubusercontent.com/14618484/28418599-8961e068-6d5c-11e7-94d5-2441ea502b7a.PNG)

file id can always be extracted from download link.

![capture2](https://user-images.githubusercontent.com/14618484/28418669-cb526074-6d5c-11e7-8189-3cd488b7e600.PNG)

**Comment by mrleadhead** [comment]
Thanks for the fast reply and sorry for being a complete novice, I need you to hold my hand a little bit more. 

I'm currently using `openload.upload_file(file)` and the file is uploaded ok. but how:

1. How do I get the HTTP response?
2. I can probably work this one out but as I have the ear of someone much better then myself how would I extract the id from the response? I'd like to be able to use this to automate embedding on a website so would need to be able to send it out to another script.

**Comment by mohan3d** [comment]
You are welcome.

```
>>> resp = openload.upload_file('file_path')
>>> print(resp)
```

dictionary like this will be printed.

![](https://user-images.githubusercontent.com/14618484/28418599-8961e068-6d5c-11e7-94d5-2441ea502b7a.PNG)

**Comment by mrleadhead** [comment]
ok I feel i'm becoming  apain now so I'll keep this short and sweet and hopefuly the last thing I ask. 

`>>> resp = openload.upload_file('file_path')
>>> print(resp`

works really well but gives me everything so I tried `print(resp).get('id')` to just get the ID but it prints "None" I think I'm close but maybe need a little more help.

Thanks for all the help so far.

**Comment by mohan3d** [comment]
You are welcome :) 

Yes you are very close,  `resp `is a dictionary with 3 keys

 `['msg', 'status', 'result']`  as you see in the above pic.

```
msg: string 
status: integer
result: dictionary
```

what you need is found in result dictionary.

instead of `print(resp.get('id'))` use `print(resp.get('result').get('id'))`.

**Comment by mrleadhead** [comment]
Ahh that makes sense!

Thanks for all your help you have been supper useful .

**Comment by mohan3d** [comment]
My pleasure.
