### ISSUE TITLE
Cannot import name OpenLoad.

### ISSUE THREAD

**Issue by mrleadhead** [mohan3d/PyOpenload#4]
Hi, 

I've Just moved my script onto my Linux debian Jessie server installed pyopenload via `pip install pyopenload` but I keep getting the error `Cannot import name OpenLoad`. Looking online they say this is a circular dependent import issue but I don't believe that is the case as the script works on my windows pc.

I've tested on another windows pc and a Ubuntu desktop, to rule out my script I use the console typed `from openload import OpenLoad` and I still get the error.

Using `help("modules")` I can see that the module is installed and I can also find the files in the python install.

Any ideas?

**Comment by mohan3d** [comment]
Hi @mrleadhead ,

How do you install pyopenload (both in windows/linux) ? 

Inside virtualenv ? `pip install pyopenload`
Or globally `sudo pip install pyopenload`

How do you run your script  (both in windows/linux) ?

If you are using virtualenv, do you run your the script after activating virtualenv ?

**Comment by mrleadhead** [comment]
pyopenload was install globally `sudo pip install pyopenload` on linux and windows 

I run it on linux via `python openload.py` and via the defult IDE on windows. 

Thanks

**Comment by mohan3d** [comment]
`python openload.py` I don't know if this is really the name of your script.

please re-name your script from `openload.py` to `myopenload.py` and try to execute it.

`python myopenload.py`

**Comment by mrleadhead** [comment]
ok that seems to have got me further  along, odd how it worked on of my work pc but none of the others. 

I now have this error that I’m struggling to understand
`root@vps:/var/www/video# python myopenload.py
Traceback (most recent call last):
  File "myopenload.py", line 8, in <module>
    resp = openload.upload_file(file)
  File "/usr/local/lib/python2.7/dist-packages/openload/openload.py", line 172, in upload_file
    response = self.upload_link(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openload/openload.py", line 156, in upload_link
    return self.__get('file/ul', params=params, result_only=result_only)
  File "/usr/local/lib/python2.7/dist-packages/openload/openload.py", line 76, in __get
    response_json = requests.get(self.api_url + url, params).json()
TypeError: get() takes exactly 1 argument (2 given)
`
This is my code 

```
from openload import OpenLoad
import os

openload = OpenLoad('XXXXXX', 'XXXXXX')

file=("wildlife.wmv")

resp = openload.upload_file(file)

os.remove(file)

id=(resp.get('result').get('id'))
```

**Comment by mohan3d** [comment]
`file=("wildlife.wmv")`

This line is the problem.

`upload_file(FILE_PATH)` the upload method should be provided with a file path not a tuple.

**Comment by mrleadhead** [comment]
I've changed the code as below but still get the error
```
from openload import OpenLoad

openload = OpenLoad('XXXXXX', 'XXXXXX')

resp = openload.upload_file()

id=(resp.get('result').get('id'))
```

Well I've certainly learnt not to test everything on windows then move it to Linux.

**Comment by mohan3d** [comment]
`resp = openload.upload_file(wildlife.wmv)`

are you sure param is `wildlife.wmv` not `'wildlife.wmv' `or `"wildlife.wmv"`

actually pyopenload was written in linux and tested on windows :D

**Comment by mrleadhead** [comment]
Sorry making stupid mistakes now I forgot to include the quotes when posting here but they are in the code.

The code looks like this. 
```
from openload import OpenLoad

openload = OpenLoad('XXXXXX', 'XXXXXX')

resp = openload.upload_file("wildlife.wmv")

id=(resp.get('result').get('id'))
```
And I still get `TypeError: get() takes exactly 1 argument (2 given)`

**Comment by mohan3d** [comment]
As I understand from this line,
`line 76, in __get response_json = requests.get(self.api_url + url, params).json() TypeError: get() takes exactly 1 argument (2 given)`

There is a problem with `requests.get()`.

I tried to install requests in a new virtualenv(both python2 and python3) and used `requests.get() ` with `3 params`.

The error message is not the same as your error.

`TypeError: get() takes from 1 to 2 positional arguments but 3 were given`

Did you install old version of requests before installing `pyopenload` ?

Can you create new virtualenv and install only pyopenload then test it with your file ?

**Comment by mrleadhead** [comment]
Thanks for your help again it seems it was an issue with my requests/python install might also be to do with debian Jessie using python 2.7.9 tested with 3.4 and it works great. 

also it's back to working with the tuple as well.

**Comment by mohan3d** [comment]
You are welcome :) 

I didn't notice that it was just string not tuple.

`file=("wildlife.wmv")` file is string not a tuple.
`file=("wildlife.wmv", )` file is a tuple (upload file will fail).
