### ISSUE TITLE
using Streaming upload 

### ISSUE THREAD

**Issue by mrleadhead** [mohan3d/PyOpenload#5]
Hi, me again. 

I have an issue whereby I'm unable to upload large files from my server as your script uses chucked uploading (as I'm sure you know this loads the file into ram) I would rather use streaming upload (that does not load into ram) 

I tried to edit your code but have had no luck I get no errors but the file also does not upload any ideas? 

```
   def upload_file(self, file_path, **kwargs):
        
        response = self.upload_link(**kwargs)
        upload_url = response['url']

        m = MultipartEncoder(fields={'field0':('filename', open(file_path, 'rb'))})

        requests.post(upload_url, data=m)
```

I've also added `stream=True` to the get request.

I'm using `requests_toolbelt` to-do this

update:

I believe the server is giving a response 500 error.

update2:

I've found the 500 error " upload failed: no boundary defined in Content-Type " I thought requests handled the header? 

I've tried adding `headers = {'content-type': 'video/mp4'}` to the post request to manually add it but no success

**Comment by mohan3d** [comment]
Sorry @mrleadhead  I was very busy didn't notice this issue.

Did you solve it?

**Comment by mrleadhead** [comment]
unfortunately not this is as far as I have gotten for now.

**Comment by mohan3d** [comment]
Hi @mrleadhead ,

If you didn't solve the problem yet,

can you provide additional info?

size of your file?

what happened in your last try? 

> I've tried adding headers = {'content-type': 'video/mp4'} to the post request to manually add it but no success

**Comment by mrleadhead** [comment]
Hi,

I haven't solved it yet not had much time to work on it. 

when using your code without the streaming upload edit, the upload fails and gives a MemoryError whenever the file is larger than my free RAM.
currently I only have 4gb install on my server.

when I add the code to stream the upload I get the error "upload failed: no boundary defined in Content-Type " even when I define the boundary manually.

**Comment by mohan3d** [comment]
I noticed this limitation from openload, it may be the problem but openload sends a wrong message.

> Up to which filesize can I upload my files?
> 
> The maximum file size is limited to 1 GB. Your files can be up to 10 GB without any restrictions if you let us convert them.

**Comment by mrleadhead** [comment]
I did notice that but I have converting on so I should have the 10 gb limit and I've only tried up to  5 gb files.

**Comment by playmusic9** [comment]
example:
```python
from requests_toolbelt.multipart import encoder
def upload_file(self, file_path, **kwargs):
        response = self.upload_link(**kwargs)
        upload_url = response['url']
        session = requests.Session()
        uploadf = open(file_path, 'rb')
        head, tail = os.path.split(file_path)
        form = encoder.MultipartEncoder({
            "files": (tail, uploadf, "application/octet-stream"),
        })
        headers = {"Prefer": "respond-async", "Content-Type": form.content_type}
        return session.post(upload_url, headers=headers, data=form).json()
```

**Comment by mohan3d** [comment]
@mrleadhead please try the example provided by @playmusic9 .

**Comment by mrleadhead** [comment]
Thanks @playmusic9 I've not had a chance to give this a go yet hopefully will this weekend but it looks good to me. I'll update you one I’ve had a go. 

I also emailed openload.co and they made some adjustments to their headers so hopefully that has helped.

**Comment by mrleadhead** [comment]
Hi sorry for taking so long to look at this.
@playmusic9  you code works perfectly.

Thank you both for all of your help.

**Comment by mohan3d** [comment]
@playmusic9 Thank you.
