### ISSUE TITLE
Error regarding no bandwith for api download

### ISSUE THREAD

**Issue by DarkXDroid** [mohan3d/PyOpenload#6]
Thre is an error that is not going away even after 7 hours from the initial testing.

Error:
openload.api_exceptions.BandwidthUsageExceeded: bandwidth usage too high (peak hours). out of capacity for non-browser downloads. please use browser download

Just letting you know guys! Thanks for this piece of code

**Comment by mohan3d** [comment]
Hi @DarkXDroid ,

You will find this line in [openload.co api general information section](https://openload.co/api#generalinformation).

> 509: Bandwidth usage exceeded. Please try again later or use Browser Download. (you might see this during peak hours)

If you look at  `_process_response` you will find

```
elif status == 509:
            raise BandwidthUsageExceeded(msg)
```

It's clear the response has status code `509` , that's why you got this exception.

**Comment by DarkXDroid** [comment]
Arright I understand! Thanks
